/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Classes;

/**
 *
 * @author gavin
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        y1TextField = new javax.swing.JTextField();
        z1TextField = new javax.swing.JTextField();
        x2TextField = new javax.swing.JTextField();
        y2TextField = new javax.swing.JTextField();
        z2TextField = new javax.swing.JTextField();
        x1TextField = new javax.swing.JTextField();
        y3TextField = new javax.swing.JTextField();
        z3TextField = new javax.swing.JTextField();
        x3TextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        b2TextField = new javax.swing.JTextField();
        b3TextField = new javax.swing.JTextField();
        b1TextField = new javax.swing.JTextField();
        calculateButton = new javax.swing.JButton();

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 30)); // NOI18N
        jLabel5.setText("X");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 30)); // NOI18N
        jLabel9.setText("+");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 2, 30)); // NOI18N
        jLabel16.setText("+");

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jTextField8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Gaussian Elimination");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 30)); // NOI18N
        jLabel2.setText("x");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 30)); // NOI18N
        jLabel3.setText("x");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 30)); // NOI18N
        jLabel4.setText("+");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 30)); // NOI18N
        jLabel6.setText("x");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 30)); // NOI18N
        jLabel7.setText("+");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 30)); // NOI18N
        jLabel8.setText("y");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 2, 30)); // NOI18N
        jLabel10.setText("+");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 2, 30)); // NOI18N
        jLabel11.setText("y");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 2, 30)); // NOI18N
        jLabel12.setText("y");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 2, 30)); // NOI18N
        jLabel13.setText("+");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 2, 30)); // NOI18N
        jLabel14.setText("+");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 2, 30)); // NOI18N
        jLabel15.setText("z");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 2, 30)); // NOI18N
        jLabel17.setText("+");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 2, 30)); // NOI18N
        jLabel18.setText("z");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 2, 30)); // NOI18N
        jLabel19.setText("z");

        y1TextField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        y1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y1TextFieldActionPerformed(evt);
            }
        });

        z1TextField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        z1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                z1TextFieldActionPerformed(evt);
            }
        });

        x2TextField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        x2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x2TextFieldActionPerformed(evt);
            }
        });

        y2TextField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        y2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y2TextFieldActionPerformed(evt);
            }
        });

        z2TextField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        z2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                z2TextFieldActionPerformed(evt);
            }
        });

        x1TextField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        x1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x1TextFieldActionPerformed(evt);
            }
        });

        y3TextField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        y3TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y3TextFieldActionPerformed(evt);
            }
        });

        z3TextField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        z3TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                z3TextFieldActionPerformed(evt);
            }
        });

        x3TextField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        x3TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x3TextFieldActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 2, 30)); // NOI18N
        jLabel20.setText("=");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 2, 30)); // NOI18N
        jLabel21.setText("=");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 2, 30)); // NOI18N
        jLabel22.setText("=");

        b2TextField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        b2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2TextFieldActionPerformed(evt);
            }
        });

        b3TextField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        b3TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3TextFieldActionPerformed(evt);
            }
        });

        b1TextField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        b1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1TextFieldActionPerformed(evt);
            }
        });

        calculateButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        calculateButton.setText("Calculate");
        calculateButton.setToolTipText("");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(x2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(y1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(y2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(y3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(z1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(z3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(z2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(6, 6, 6)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(y1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(z1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(x1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(b1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(x2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(y2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(jLabel20)
                                .addComponent(b2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel13)
                            .addComponent(z2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(x3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel19)
                            .addComponent(y3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(z3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(b3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        try{
        BigFraction x1 = new BigFraction(Integer.parseInt(x1TextField.getText()), 1);
        BigFraction y1 = new BigFraction(Integer.parseInt(y1TextField.getText()), 1);
        BigFraction z1 = new BigFraction(Integer.parseInt(z1TextField.getText()), 1);
        BigFraction b1 = new BigFraction(Integer.parseInt(b1TextField.getText()), 1);
        BigFraction x2 = new BigFraction(Integer.parseInt(x2TextField.getText()), 1);
        BigFraction y2 = new BigFraction(Integer.parseInt(y2TextField.getText()), 1);
        BigFraction z2 = new BigFraction(Integer.parseInt(z2TextField.getText()), 1);
        BigFraction b2 = new BigFraction(Integer.parseInt(b2TextField.getText()), 1);
        BigFraction x3 = new BigFraction(Integer.parseInt(x3TextField.getText()), 1);
        BigFraction y3 = new BigFraction(Integer.parseInt(y3TextField.getText()), 1);
        BigFraction z3 = new BigFraction(Integer.parseInt(z3TextField.getText()), 1);
        BigFraction b3 = new BigFraction(Integer.parseInt(b3TextField.getText()), 1);
        
        BigFraction[][] matrix = {
        {x1, y1, z1, b1},
        {x2, y2, z2, b2},
        {x3, y3, z3, b3}
        };
        toRowEchelon(matrix);
        RowEchelon RowEchelonFrame = new RowEchelon();
        javax.swing.JLabel[][] labelMatrix = {
        {RowEchelonFrame.x1Label, RowEchelonFrame.y1Label, RowEchelonFrame.z1Label, RowEchelonFrame.b1Label},
        {RowEchelonFrame.x2Label, RowEchelonFrame.y2Label, RowEchelonFrame.z2Label, RowEchelonFrame.b2Label },
        {RowEchelonFrame.x3Label, RowEchelonFrame.y3Label, RowEchelonFrame.z3Label, RowEchelonFrame.b3Label }
    };
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 4; j++) {
                if (matrix[i][j].getDenominator().equals(java.math.BigInteger.ONE)){
                    labelMatrix[i][j].setText(matrix[i][j].getNumerator().toString());
                }
                else {
                    labelMatrix[i][j].setText(matrix[i][j].toString());
                }
            }
        }
        RowEchelonFrame.solutionPanel.setVisible(false);
        RowEchelonFrame.unsolvableLabel.setVisible(false);
        if (isSolvable(matrix)){
            RowEchelonFrame.solutionPanel.setVisible(true);
            BigFraction[] solution = solve(matrix);
            javax.swing.JLabel[] solutionLabels = {RowEchelonFrame.xLabel, RowEchelonFrame.yLabel, RowEchelonFrame.zLabel};
            for (int i = 0; i < 3; i++){
                if (solution[i].getDenominator().equals(java.math.BigInteger.ONE))
                    solutionLabels[i].setText(solution[i].getNumerator().toString());
                else
                    solutionLabels[i].setText(solution[i].toString());
            }
        }
        else{
            RowEchelonFrame.unsolvableLabel.setVisible(true);
            if (!matrix[2][3].equals(BigFraction.ZERO))
                RowEchelonFrame.unsolvableLabel.setText("No Solution");
        }
        dispose();
        RowEchelonFrame.show();
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_calculateButtonActionPerformed
    public static void toRowEchelon(BigFraction[][] matrix){
        sort(matrix);
        //First Step
        if (!matrix[1][0].equals(BigFraction.ZERO)){
            BigFraction multiplier = matrix[1][0].divide(matrix[0][0]).negate();
            matrix[1] = combine(multiplier, matrix[0], matrix[1]);
        }
        if (!matrix[2][0].equals(BigFraction.ZERO)){
            BigFraction multiplier = matrix[2][0].divide(matrix[0][0]).negate();
            matrix[2] = combine(multiplier, matrix[0], matrix[2]);
        }
        sort(matrix);

        //Second Step
        if (!matrix[2][1].equals(BigFraction.ZERO)){
            BigFraction multiplier = matrix[2][1].divide(matrix[1][1]).negate();
            matrix[2] = combine(multiplier, matrix[1], matrix[2]);
        }
    }
        public static BigFraction[] combine(BigFraction multiplier, BigFraction[] row1, BigFraction[] row2){
        BigFraction[] combined = new BigFraction[4];
        for (int i = 0; i < combined.length; i++) {
            combined[i] = (multiplier.multiply(row1[i])).add(row2[i]);
        }
        return combined;
    }

    public static void sort(BigFraction[][] matrix){
        for (int i = 0; i < 3; i++) {
            if (!matrix[i][0].equals(BigFraction.ZERO)){
                rowSwap(matrix, 0, i);
                break;
            }
        }
        for (int i = 1; i < 3; i++) {
            if (!matrix[i][1].equals(BigFraction.ZERO)){
                rowSwap(matrix, 1, i);
                break;
            }
        }
    }
    public static boolean isSolvable(BigFraction[][] matrix){
        return !matrix[2][2].equals(BigFraction.ZERO);
    }
    public static BigFraction[] solve(BigFraction[][] matrix){
        BigFraction z = matrix[2][3].divide(matrix[2][2]);
        BigFraction y = (matrix[1][3].subtract(matrix[1][2].multiply(z))).divide(matrix[1][1]);
        BigFraction x = (matrix[0][3].subtract(matrix[0][1].multiply(y)).subtract(matrix[0][2].multiply(z))).divide(matrix[0][0]);
        return new BigFraction[]{x, y, z};
    }
    
    public static void rowSwap(BigFraction[][] matrix, int row1Index, int row2Index){
        BigFraction[] row = matrix[row1Index];
        matrix[row1Index] = matrix[row2Index];
        matrix[row2Index] = row;
    }
    public static void printMatrix(BigFraction[][] matrix){
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 4; j++) {
                if (matrix[i][j].getDenominator().equals(java.math.BigInteger.ONE)){
                    System.out.print(matrix[i][j].getNumerator());
                }
                else {
                    System.out.print(matrix[i][j]);
                }
                System.out.print("  ");
            }
            System.out.println();
        }
    }
    private void y1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y1TextFieldActionPerformed

    private void z1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_z1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_z1TextFieldActionPerformed

    private void x2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x2TextFieldActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void y2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y2TextFieldActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void z2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_z2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_z2TextFieldActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void x1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x1TextFieldActionPerformed

    private void y3TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y3TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y3TextFieldActionPerformed

    private void z3TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_z3TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_z3TextFieldActionPerformed

    private void x3TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x3TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x3TextFieldActionPerformed

    private void b2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2TextFieldActionPerformed

    private void b3TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3TextFieldActionPerformed

    private void b1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1TextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b1TextField;
    private javax.swing.JTextField b2TextField;
    private javax.swing.JTextField b3TextField;
    private javax.swing.JButton calculateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField x1TextField;
    private javax.swing.JTextField x2TextField;
    private javax.swing.JTextField x3TextField;
    private javax.swing.JTextField y1TextField;
    private javax.swing.JTextField y2TextField;
    private javax.swing.JTextField y3TextField;
    private javax.swing.JTextField z1TextField;
    private javax.swing.JTextField z2TextField;
    private javax.swing.JTextField z3TextField;
    // End of variables declaration//GEN-END:variables
}
